### ISSUE TITLE
Resolve Dependency Situation With Spark

### ISSUE THREAD

**Issue by timothyrenner** [timothyrenner/ProfanityPowerIndex#1]
Spark streaming is packaged with an older version of jets3t to write to S3. I think the bundled Hadoop distro might have or require a newer version, which is causing a runtime error whenever the program tries to write to S3.

**Comment by timothyrenner** [comment]
I'm using Spark 1.4.1 pre-built for Hadoop 2.6 locally, which is where I see the exception.

```
... java.lang.NoSuchMethodError: org.jets3t.service.impl.rest.httpclient.RestS3Service.<init>(Lorg/jets3t/service/security/AWSCredentials;)V
at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.initialize(Jets3tNativeFileSystemStore.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:85)
```

**Comment by jimitkr** [comment]
I added Hadoop 2.6.0 libraries to my code which came with jets3t0.9.0. I still get the same error. What do i do? What would be the correct jets3t jar to use?

**Comment by timothyrenner** [comment]
Honestly I have no idea. I copped out on S3 because I couldn't solve this before I needed to use it. I tried manually adding 0.9 to the classpath but it got clobbered by whatever was in the binary near as I could tell. I had to install [`sbt-dependency-graph`](https://github.com/jrudolph/sbt-dependency-graph) to figure that one out.

 I'll poke around a little bit this week and see what I can find.

**Comment by jimitkr** [comment]
Just found out this problem has something to do with the Hadoop 2.6<--> S3 issue raised here:
https://issues.apache.org/jira/browse/SPARK-7442

Like others, i used Spark for Hadoop 2.4 and got things to work for now. Will wait to see if the original issue resolves soon :)

**Comment by timothyrenner** [comment]
Nice! Thanks for pointing that out!

**Comment by timothyrenner** [comment]
No longer using spark :tada: - problem solved.
